### PR TITLE
feat: bundle sizes tab (bundled+minified+gzipped)

### LINKED ISSUE #74: REPL — show compiled/bundled size
Has to be done in a way that doesn't cause premature concern about duplication etc. Should include min/zip sizes

### PR DESCRIPTION
**Pull request by bcharbonnier**
Introducing a new tab in the Output section regarding bundle sizes.

image

The PR introduces a new Worker `sizes.js` in charge of computing different various sizes which are all detailed using KB (aka [Kibibytes](https://en.wikipedia.org/wiki/Kibibyte))
The worker is then used via a Class `Sizes.js`. The entire computation is started by listenning the `$bundle` store, and generate the corresponding sizes:
- Sources: aggregate all source files
- Compiled: size of the generated bundle
- Minified: using Terser (imported in the worker from unpkg) on the compiled code.
- Gzipped: using Pako (imported in the worker from unpkg) on the minified code.

These sizes are then stored into a new store `bundleSizes` that I added to the REPL Context.

Finally `BundleSizes.svelte` listen to this `bundleSizes` stores and display everything.

All bytes sizes are computed using `TextEncoder` class to make sure we consider all utf things properly.

---

To be honest I didn't  take the time to actually validates the number in an empiric way. They seemed right in the first place.
I could perform this check if needed.

Closes #74

### CODE REVIEW

**Comment by bcharbonnier** [comment]
anyone to review this ? 🙏

**Comment by Rich-Harris** [comment]
Thank you! Apologies for the slow review.

I think exposing bundle size is a great idea, and the new tab looks nice. I think we need to account for the options in the JS output tab though — right now, it's just using the bundle that's generated for the 'Result' tab, which among other things is always compiled with `dev: true`, which makes the output size slightly misleading.

I think we probably want the output sizes to be in the 'JS Output' tab, and for them to reflect the options set in that tab (e.g. it's nice to be able to see what effect `hydratable: true` has). That might mean that we need to bundle with those options in the first place? Which I guess would make sense, though it would mean slightly further-reaching changes (like just setting `innerHTML` in `generate: 'ssr'` mode, rather than creating a client-side component).

Since we're showing source size, we *might* want to also include CSS output size, though that may be making things unnecessarily complicated.

**Comment by bcharbonnier** [comment]
Thank you very much for the review and all the detailed explanations for improvement (or correction I should say!)

I could use a couple more info though:

> That might mean that we need to bundle with those options in the first place?

I probably should introduce a new dedicated bundler (ie not reusing the one used by Result Tab) reflecting these options.
As you mentioned, we could show differences between "dom" and "ssr" generation <-- is it what your remark about `innerHTML` is about ? I am not sure I completely get that point your raised...

Would it actually make sense to always perform a dual build (dom+ssr) ? I am not sure. We could only reflect based on the selected options.

> I think we probably want the output sizes to be in the 'JS Output' tab, and for them to reflect the options set in that tab

Does it mean we should get rid of the `Bundle sizes` Tab ?
My main thought was to show the overall size of the bundle, sizes per component would give extra info, but for me in the end, final bundle is what matters.

If we move something  to `JS Output`, I would rather add yet anoter collapsible section (or new tab sibling to compiler option) showing `Size stats` for each component, that could display what you described -> influence of all compiler options. I'll try to figure out something nice for that.

Great! Let's do this 😄

**Comment by Rich-Harris** [comment]
Sorry, I dropped the ball on this. This repo is going to be deprecated, so I'll close this in favour of https://github.com/sveltejs/sites/issues/129

**Pull request closed without merging**
