### PR TITLE
manage editor undo history

### PR DESCRIPTION
**Pull request by tanhauhau**
Fixes https://github.com/sveltejs/svelte-repl/issues/3

- keep track and preserve undo history across tabs

undo-buffer

### CODE REVIEW

**Comment by Conduitry** [comment]
This is definitely a great start but it doesn't seem to be quite working. If I go into the 'examples' section of the site, for example, and click around between different examples, I can then repeatedly ctrl-z in one example's App.svelte to make it look like previous examples' App.svelte. This is certainly better than what we have now, but I'm hoping that we can also just clear the undo history for all tabs when the REPL consumer updates its contents.

**Comment by tanhauhau** [comment]
handled that now. can give it a try.

**Comment by Conduitry** [comment]
From the homepage, if I click directly to the REPL, loading the Hello World example, and then ctrl-z in the editor, the text disappears. Apparently it's starting empty and going from empty to Hello World is seen as an undoable action. Is it possible to clear the undo buffer in this situation as well?

**Comment by tanhauhau** [comment]
wow.. good catch! fixed.

**Pull request merged**
