### PR TITLE
add the remaining console utils

### PR DESCRIPTION
**Pull request by tanhauhau**
- console.count, console.countReset [Repl](https://svelte.dev/repl/04409d0bfdb346d5bd96c39b0c4e446a?version=3.20.1)

Screenshot 2020-04-15 at 6 51 23 PM

- console.trace [Repl](https://svelte.dev/repl/257d10ed7a3b47a8af695c076ca8578a?version=3.20.1)

Screenshot 2020-04-15 at 6 48 01 PM

- console.assert [Repl](https://svelte.dev/repl/97def118689244ca9bcd0a7c99bf0bda?version=3.20.1)

Screenshot 2020-04-15 at 6 52 56 PM

- console.time, console.timeLog, console.timeEnd [Repl](https://svelte.dev/repl/2a5ab609c01b4929a2b11cca67086846?version=3.20.1)

Screenshot 2020-04-15 at 6 49 40 PM

### CODE REVIEW

**Comment by Conduitry** [comment]
The `console.assert()` example throws an 'object could not be cloned' exception in Firefox, because [its structured clone algorithm does not support native error types](https://bugzilla.mozilla.org/show_bug.cgi?id=1556604).

**Comment by tanhauhau** [comment]
Screenshot 2020-04-15 at 11 22 13 PM

**Comment by tanhauhau** [comment]
fixed for firefox!

**Comment by Conduitry** [comment]
I don't see any additional changes pushed.

**Comment by tanhauhau** [comment]
oops. 🙈

**Comment by Conduitry** [comment]
I no longer see a collapsible stacktrace with `console.assert` - was this intentional?

**Comment by tanhauhau** [comment]
oops you are right. im adding them back.

**Pull request merged**
