### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by tanhauhau**

### CODE REVIEW

**Comment by anotherjesse** [comment]
Unfortunately this doesn't work for me.

git clone / npm install / npm run srcdoc are successful, and I can run `npm run dev` but rollup doesn't end up listening on 5000:

I see the following in my terminal:

```
rollup v1.27.0
bundles src/workers/compiler/index.js → workers/compiler.js...
created workers/compiler.js in 28ms
bundles src/workers/bundler/index.js → workers/bundler.js...
created workers/bundler.js in 1.3s

[2019-11-14 22:18:42] waiting for changes...
```

Here is my node info - perhaps my system doesn't have the right requirements?

```
% npm version
{
  '@sveltejs/svelte-repl': '0.1.13',
  npm: '6.11.3',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.39.2',
  node: '12.12.0',
  openssl: '1.1.1d',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.32.0',
  v8: '7.7.299.13-node.12',
  zlib: '1.2.11'
}
```

**Comment by tanhauhau** [comment]
oh i just realised that there's no server in this repo to view the changes.

the `yarn dev` is just develop the repl widget. you have to `npm link` this into `svelte/site/node_modules` folder to see it in action

**Comment by Conduitry** [comment]
It'd be good if this repo contained a simple app that consumes the REPL and lets it be served standalone, but in the meantime we should probably mention that you can `npm link` it into the Svelte site.

I also think most of this information actually belongs in the main readme, as the `npm run srcdoc` thing especially is unintuitive.

**Comment by hackape** [comment]
I'm considering converting this repl into a vscode extension and stumble over this issue. Just filed #118 to setup a standalone demo app. Hope you guys consider it. @tanhauhau @Conduitry

**Comment by Rich-Harris** [comment]
Closing as out of date — we should add some guidelines on https://github.com/sveltejs/sites instead

**Pull request closed without merging**
