### PR TITLE
Prevent duplication of the same component name

### LINKED ISSUE #36: Reserved tab name "App" causes issues
1. Create a new tab.
2. Try to name it "Append".
3. Note how after typing "App", the input field loses focus and the new tab is no longer deleteable nor renameable.

I assume this is due to the name state updating with each `input` event. Possible solutions would include only updating the name on `blur` or not identifying the "main" tab by its name (but instead, for example, by its index).

### PR DESCRIPTION
**Pull request by donnisnoni95**
- [x] FIX #36  , thanks to @loilo  👏 for his solution.
- [x] Removing component by passing `index` as parameter instead passing  `component` as parameter and using `indexOf` again.
- [x] Preventing creating a new component with the same name as the existing components name.

### CODE REVIEW

**Comment by donnisnoni95** [comment]
@Conduitry, @Rich-Harris can we ship this ???

**Comment by donnisnoni95** [comment]
@Conduitry is my code bad ???

**Comment by tanhauhau** [comment]
hmm... why is this closed?

**Comment by donnisnoni95** [comment]
@tanhauhau Hai... ya.. I closed this because I think they don't need it.  😊

**Comment by loilo** [comment]
That's a decently bold statement to make without anybody making a comment on it. 🤔

**Comment by tanhauhau** [comment]
Hmm.. well since you closed yours, I've created another PR https://github.com/sveltejs/svelte-repl/pull/60 to fix this.
Cause it's kind of a annoying bug to behavior

**Pull request closed without merging**
